### ISSUE TITLE
API allowing a DataSource to add functions to Chrome's ContextMenu 

### ISSUE THREAD

**Issue by rorybyrne** [MetroPlatform/Metro-BrowserExtensionArchived#8]
DataSources run in content scripts, which means they do not have direct access to Chrome APIs like `contextMenu` (right-click menu) the way that background scripts do. This means that a DataSource cannot create a `contextMenu` button without some help from the core Metro background script. 

It's possible to communicate between content scripts and background scripts using Chrome messaging so I propose we implement functions in the MetroClient which allows a user to add, update, and remove `contextMenu` items.

**Comment by conor-f** [comment]
We already use the messaging to send datapoints. There's another change that has to be made to load the Datasource scripts from the background anyways as it will give us security benefits so it makes sense to have these two changes go hand in hand.

The best way to do this is probably to flesh out the MetroClient object and have a handler that will get run when the Datasource is loaded to modify the context menu. Will make new issues for each of these in the next few days.
